@include('emails.layouts.review', [
    'url' => $url,
    'user' => $user,
    'pageTitle' => '비밀번호 재설정 — PAC RUN REVIEW',
    'preheader' => '비밀번호 재설정 링크가 도착했습니다. 60분 내에 새 비밀번호를 설정해 주세요.',
    'accent' => '#E80043',
    'bandBg' => '#E80043',
    'bandColor' => '#FFFFFF',
    'bandLabel' => 'PASSWORD RESET REQUEST — ACTION REQUIRED',
    'badgeColor' => '#E80043',
    'colRuleColor' => '#E80043',
    'ctaBg' => '#E80043',
    'ctaText' => '#FFFFFF',
    'urlLabelColor' => '#E80043',
    'urlBorderColor' => '#E80043',
    'urlLinkLabel' => 'RESET LINK',
    'headerTag' => 'SECURITY ALERT',
    'headerTagColor' => '#E80043',
    'messageBorder' => '#FFD0D8',
    'badge' => 'PASSWORD RESET',
    'watermark' => '!',
    'heroTitleHtml' => '비밀번호 <em style="font-style:italic;font-weight:400;color:#E80043;">재설정</em><br>요청',
    'heroDesc' => 'ACCOUNT SECURITY / RESET PASSWORD / EXPIRES IN 60 MINUTES',
    'eyebrow' => '비밀번호 재설정 안내',
    'messageHtml' => '비밀번호 재설정 요청이 접수되었습니다.<br>아래 버튼을 클릭하여 새로운 비밀번호를 설정해 주세요.<br>본인이 요청하지 않은 경우 이 메일을 무시하시면 됩니다.',
    'ctaLabel' => '비밀번호 재설정하기',
])
