@include('emails.layouts.review', [
    'url' => $url,
    'user' => $user,
    'pageTitle' => '이메일 인증 — PAC RUN REVIEW',
    'preheader' => 'PAC RUN REVIEW 가입을 환영합니다. 이메일 인증을 완료해 주세요.',
    'accent' => '#1A1212',
    'bandBg' => '#E5AD16',
    'bandColor' => '#1A1212',
    'bandLabel' => 'MARATHON &amp; RUNNING RACE REVIEW PLATFORM',
    'badgeColor' => '#E5AD16',
    'colRuleColor' => '#1A1212',
    'ctaBg' => '#1A1212',
    'ctaText' => '#F5EFE3',
    'urlLabelColor' => '#C09010',
    'urlBorderColor' => '#E5AD16',
    'urlLinkLabel' => 'DIRECT LINK',
    'headerTag' => 'RACE REVIEW',
    'headerTagColor' => '#E5AD16',
    'messageBorder' => '#E8E0D0',
    'badge' => 'EMAIL VERIFICATION',
    'watermark' => '01',
    'heroTitleHtml' => '이메일 <em style="font-style:italic;font-weight:400;color:#E5AD16;">인증</em><br>요청',
    'heroDesc' => 'ACCOUNT VERIFICATION / STEP 01 OF 01',
    'eyebrow' => '이메일 인증 안내',
    'messageHtml' => 'PAC RUN REVIEW에 가입해주셔서 감사합니다.<br>아래 버튼을 클릭하여 이메일 인증을 완료하면<br>리뷰 작성 및 모든 서비스를 이용하실 수 있습니다.',
    'ctaLabel' => '이메일 인증하기',
])
